name = "MeshesToolbox"
uuid = "f5c3dc73-c322-4b0e-9e6f-8420cbe222d2"
authors = ["Veenty <vicentegomezh@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
